module.exports = {
  googleIcon: require('@assets/images/auth/google.png'),
  fbIcon: require('@assets/images/auth/fb.png'),
  appleIcon: require('@assets/images/auth/apple.png'),
  editIcon: require('@assets/images/auth/edit.png'),

  onBoarding1: require('@assets/images/onBoarding/onBoarding1.png'),
  onBoarding2: require('@assets/images/onBoarding/onBoarding2.png'),
  onBoarding3: require('@assets/images/onBoarding/onBoarding3.png'),
  logo: require('@assets/images/logo/ss/sslogo.png'),
  darkLogo: require('@assets/images/logo/sslogo.png'),
  divider: require('@assets/images/divider.png'),
  darkDivider: require('@assets/images/darkDivider.png'),
  user: require('@assets/images/image/user.png'),

  dealOfTheDay1: require('@assets/images/home/home_deals/dealOfTheDay1.png'),
  dealOfTheDay2: require('@assets/images/home/home_deals/dealOfTheDay2.jpeg'),
  dealOfTheDay3: require('@assets/images/home/home_deals/dealOfTheDay3.png'),

  findStyle1: require('@assets/images/home/find_style/findStyle1.png'),
  findStyle2: require('@assets/images/home/find_style/findStyle2.png'),
  findStyle3: require('@assets/images/home/find_style/findStyle3.png'),
  findStyle4: require('@assets/images/home/find_style/findStyle4.png'),
  findStyle5: require('@assets/images/home/find_style/findStyle5.png'),

  banner1Image: require('@assets/images/home/home_banner/1.png'),
  banner2Image: require('@assets/images/home/home_banner/2.png'),
  banner3Image: require('@assets/images/home/home_banner/3.png'),

  homeDivider: require('@assets/images/home/divider.png'),
  denimWear: require('@assets/images/home/denimWear.png'),

  biggestDeal1: require('@assets/images/home/biggest_deal/biggestDeal1.png'),
  biggestDeal2: require('@assets/images/home/biggest_deal/biggestDeal2.png'),
  biggestDeal3: require('@assets/images/home/biggest_deal/biggestDeal3.png'),
  biggestDeal4: require('@assets/images/home/biggest_deal/biggestDeal4.png'),
  biggestDeal5: require('@assets/images/home/biggest_deal/biggestDeal5.png'),
  biggestDeal6: require('@assets/images/home/biggest_deal/biggestDeal6.png'),
  biggestDeal7: require('@assets/images/home/biggest_deal/biggestDeal7.png'),
  biggestDeal8: require('@assets/images/home/biggest_deal/biggestDeal8.png'),
  biggestDeal9: require('@assets/images/home/biggest_deal/biggestDeal9.png'),
  biggestDealDark1: require('@assets/images/home/biggest_deal/biggestDealDark1.png'),
  biggestDealDark2: require('@assets/images/home/biggest_deal/biggestDealDark2.png'),
  biggestDealDark3: require('@assets/images/home/biggest_deal/biggestDealDark3.png'),
  biggestDealDark4: require('@assets/images/home/biggest_deal/biggestDealDark4.png'),
  biggestDealDark5: require('@assets/images/home/biggest_deal/biggestDealDark5.png'),
  biggestDealDark6: require('@assets/images/home/biggest_deal/biggestDealDark6.png'),

  category1: require('@assets/images/category/1.png'),
  category2: require('@assets/images/category/2.png'),
  category3: require('@assets/images/category/3.png'),
  category4: require('@assets/images/category/4.png'),
  category5: require('@assets/images/category/5.png'),
  category6: require('@assets/images/category/6.png'),
  category7: require('@assets/images/category/7.png'),
  category8: require('@assets/images/category/8.png'),
  category9: require('@assets/images/category/9.png'),
  category10: require('@assets/images/category/10.png'),
  category11: require('@assets/images/category/11.png'),
  category12: require('@assets/images/category/12.png'),
  category13: require('@assets/images/category/13.png'),
  category14: require('@assets/images/category/14.png'),
  settings: require('@assets/images/setting.jpeg'),

  kidsCorner1: require('@assets/images/home/kids_corner/kidsCorner1.jpeg'),
  kidsCorner2: require('@assets/images/home/kids_corner/kidsCorner2.jpeg'),
  kidsCorner3: require('@assets/images/home/kids_corner/kidsCorner3.jpeg'),

  emptyStar: require('@assets/images/image/emptyStar.png'),
  filledStar: require('@assets/images/image/filledStar.png'),
  map: require('@assets/images/image/map.png'),
  darkMap: require('@assets/images/image/mapDark.png'),
  person: require('@assets/images/image/avtar.png'),
  person1: require('@assets/images/image/avtar1.png'),
  aboutUs: require('@assets/images/image/aboutUs.png'),
  helpCenter: require('@assets/images/image/helpCenter.png'),
  darkmapsection: require('@assets/images/product/darkmapsection.png'),

  sale: require('@assets/images/sale.gif'),

  truckDelivery: require('@assets/images/gif/truckDelivery.gif'),

  product1: require('@assets/images/product/product1.png'),
  product2: require('@assets/images/product/product2.png'),
  product3: require('@assets/images/product/product3.jpg'),
  product4: require('@assets/images/product/product4.png'),
  product5: require('@assets/images/product/product5.jpg'),
  product6: require('@assets/images/product/product6.jpg'),
  product7: require('@assets/images/product/product7.jpg'),
  product8: require('@assets/images/product/product8.jpg'),
  product9: require('@assets/images/product/product9.jpg'),
  product10: require('@assets/images/product/product10.jpg'),
  product11: require('@assets/images/product/product11.jpeg'),
  product12: require('@assets/images/product/product12.jpeg'),
  product13: require('@assets/images/product/product13.jpeg'),
  product14: require('@assets/images/product/product14.jpg'),
  product15: require('@assets/images/product/product15.jpg'),
  product16: require('@assets/images/product/product16.jpg'),
  product17: require('@assets/images/product/product17.png'),
  product18: require('@assets/images/product/product18.png'),
  product19: require('@assets/images/product/product19.png'),
  product20: require('@assets/images/product/product20.png'),
  product21: require('@assets/images/product/product21.png'),
  product22: require('@assets/images/product/product22.png'),
  mapImage: require('@assets/images/product/mapSection.png'),
  coupenCode: require('@assets/images/product/coupenCode.png'),

  brand1: require('@assets/images/brands/brand1.png'),
  brand2: require('@assets/images/brands/brand2.png'),
  brand3: require('@assets/images/brands/brand3.png'),
  brand4: require('@assets/images/brands/brand4.png'),
  brand5: require('@assets/images/brands/brand5.png'),
  brand6: require('@assets/images/brands/brand6.png'),

  emptyCart: require('@assets/images/emptyCart.png'),
  checkCircle: require('@assets/images/gif/checkCircle.gif'),
  cancelCircle: require('@assets/images/gif/circlecancel.png'),
  noData: require('@assets/images/noData.png'),

  cash: require('@assets/images/paymentIcon/cash.png'),
  credit: require('@assets/images/paymentIcon/credit.png'),
  netBanking: require('@assets/images/paymentIcon/netBanking.png'),
  wallets: require('@assets/images/paymentIcon/wallets.png'),
  cashDark: require('@assets/images/paymentIcon/cashDark.png'),
  creditDark: require('@assets/images/paymentIcon/creditDark.png'),
  netBankingDark: require('@assets/images/paymentIcon/netBankingDark.png'),
  walletsDark: require('@assets/images/paymentIcon/walletsDark.png'),
  copy: require('@assets/images/paymentIcon/copy.png'),

  blueCard: require('@assets/images/paymentCard/blueCard.png'),
  logo: require('@assets/images/paymentCard/logo.png'),
  purpleCard: require('@assets/images/paymentCard/purpleCard.png'),
  yellowCard: require('@assets/images/paymentCard/yellowCard.png'),
  chipImg: require('@assets/images/paymentCard/chipImg.png'),
  paytmLogo: require('@assets/images/paymentCard/paytmlogo.png'),
  googleLogo: require('@assets/images/paymentCard/Google.png'),
  cashLogo: require('@assets/images/paymentCard/cashLogo.png'),
};
